source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
gem "roo", "~> 2.8.0"
gem "rubyXL"
gem 'crack'
gem 'xml-to-json'
gem 'json'
gem 'videotime'
gem 'webpacker', '~> 4.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'rails_admin', '~> 2.0'
gem 'devise'
gem 'cancan'
gem 'tinymce-rails'
gem 'streamio-ffmpeg'

gem 'bootstrap'
gem 'acts-as-taggable-on', '~> 7.0'
gem 'jquery-rails'
gem 'chosen-rails'
gem 'fcm'
gem 'whenever', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'shoulda-matchers', '~> 4.0'
end

group :test do
  gem "webmock"
  gem 'database_cleaner-active_record'
  gem "factory_bot_rails"
  gem 'faker', '~> 1.6', '>= 1.6.6'
  gem 'rails-controller-testing'
  gem 'stub_env'
end

group :development do
  gem 'annotate'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_dashboard-9a14cb77', '0.0.2', require: 'bx_block_dashboard'
gem 'bx_block_profile-a9d74b49', '0.0.3', require: 'bx_block_profile'
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.1', require: 'bx_block_push_notifications'
gem 'account_block', '0.0.19'
gem 'bx_block_login-3d0582b5', '0.0.6', require: 'bx_block_login'
gem 'bx_block_roles_permissions-c50949d0', '0.0.5', require: 'bx_block_roles_permissions'
gem 'bx_block_forgot_password-4de8968b', '0.0.4', require: 'bx_block_forgot_password'
gem 'bx_block_filter_items-b1be1f37', '0.0.1', require: 'bx_block_filter_items'
gem 'bx_block_categories-acd0763f', '0.0.4', require: 'bx_block_categories'
gem 'bx_block_data_import_export_csv-ec567cbb', '0.0.1', require: 'bx_block_data_import_export_csv'
gem 'builder_base', '0.0.34'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'httparty'
gem 'omniauth'
gem 'globalize', '~> 5.3.0'
gem 'rails_admin_globalize_field', '~> 1.0'
gem 'carrierwave', '~> 2.0'
gem 'carrierwave-aws'
# to install elastic search(follow step 1 & 2 in below link)
# https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-18-04
gem 'searchkick'
gem 'dotenv-rails'
gem 'fog-aws'
gem "mini_magick"
gem 'geocoder', '~> 1.3', '>= 1.3.7'
