default: &default
  api_access_key: <%= ENV['API_ACCESS_KEY'] || "8563cdbe371eb26c72d9d310c13713db75ff5665df07c23a08" %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
